service: cognicity-sensors

custom:
  projectName: cognicity-sensors

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  stackTags:
    area: "US"

# You can overwrite defaults by adding the following
#  stage: dev
#  region: us-east-1

# Add one function for each Lambda
functions:
  sensorsWebhook: # Lambda that gets triggered when user starts a conversation with Twitter Messenger bot
    handler: bin/functions/sensors/index.sensors
    environment:
        PGHOST: '127.0.0.1'
        PGDATABASE: 'cognicity'
        PGPASSWORD: 'p@ssw0rd'
        PGPORT: 5432
        PGSSL: 'true'
        PGTIMEOUT: 10000
        PGUSER: 'postgres'
    events:
      - http:
          path: sensors
          method: GET # This webhook lambda is called by twitter to verify the bot
          integration: lambda
